services:
  go-test:
    build:
      context: .
      dockerfile: container-image/Dockerfile.dev
    working_dir: /src
    environment:
      - GOPATH=/go
      - METALEG_TEST_NETLINK=yes
    volumes:
      - .:/src
      - go-deps:/go
    cap_add:
      - NET_ADMIN
    entrypoint:
      - sh
      - -c
      - |
        echo "Test environment:"
        uname -a
        go version
        ip -V
        ipset --version
        iptables --version

        echo
        echo "Running tests..."
        go test "$@"
    command:
    - -v
    - "./..."

volumes:
  go-deps:
