---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: metaleg-agent
  namespace: metallb-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: metaleg
      app.kubernetes.io/component: agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: metaleg
        app.kubernetes.io/component: agent
    spec:
      serviceAccountName: metaleg-agent
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoExecute
        operator: Exists
      hostNetwork: true
      hostPID: true
      containers:
      - name: metaleg-agent
        image: ghcr.io/gerolf-vent/metaleg-agent:v0.1.0
        imagePullPolicy: Always
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: METALLB_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: FIREWALL_MASK
          value: "0x00F00000"
        - name: ROUTE_TABLE_ID_OFFSET
          value: "100000"
        - name: FIREWALL_BACKEND
          value: "iptables"
        - name: ROUTE_BACKEND
          value: "netlink"
        - name: RECONCILIATION_INTERVAL
          value: "5m"
