---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: metaleg-agent
  namespace: metallb-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: metaleg
      app.kubernetes.io/component: agent
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: metaleg
        app.kubernetes.io/component: agent
    spec:
      serviceAccountName: metaleg-agent
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoExecute
        operator: Exists
      hostNetwork: true
      hostPID: true
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: metaleg-agent
        image: ghcr.io/gerolf-vent/metaleg-agent:0.2.0
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
            add:
            - NET_ADMIN
            - NET_RAW
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        ports:
        - containerPort: 21793
          name: metrics
          protocol: TCP
        - containerPort: 21794
          name: health
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 21794
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /readyz
            port: 21794
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: METALLB_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: FIREWALL_MASK
          value: "0x00F00000"
        - name: ROUTE_TABLE_ID_OFFSET
          value: "100000"
        - name: FIREWALL_BACKEND
          value: "iptables"
        - name: ROUTE_BACKEND
          value: "netlink"
        - name: RECONCILIATION_INTERVAL
          value: "5m"
        - name: METRICS_BIND_ADDRESS
          value: ":21793"
        - name: HEALTH_PROBE_BIND_ADDRESS
          value: ":21794"
      terminationGracePeriodSeconds: 30
      priorityClassName: system-node-critical
