---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service-account.yaml
- rbac.yaml
- daemonset.yaml
labels:
  - pairs:
      app.kubernetes.io/name: metaleg
      app.kubernetes.io/version: "0.1.0"
      app.kubernetes.io/component: agent
    includeSelectors: true
