---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: metaleg:agent
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - nodes
      - endpoints
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - "discovery.k8s.io"
    resources:
      - endpointslices
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "metallb.io"
    resources:
      - servicel2statuses
    verbs:
      - get
      - list
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: metaleg:agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metaleg:agent
subjects:
- kind: ServiceAccount
  name: metaleg-agent
  namespace: metallb-system
